import: definition.yaml

concurrency:
  task:
    medagentbench-std: 1
  agent:
    gpt-4o-mini: 5

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - gpt-4o-mini
    task:
      - medagentbench-std

output: "outputs/{TIMESTAMP}"
